"""Google News editions and native-language query banks.

The global English edition misses most of what happens in a country's own press.
Querying each edition in its own language finds the ministry statement in Yerevan,
the mining-licence story in Astana, the concession row in Lima - before any of it
is translated, if it ever is. Titles come back in the source language; the
extraction stage produces the English headline.

Each edition: (label, hl, gl, ceid, language key). Each language: three
compact OR-queries - forum terms, distress terms, treaty terms.
"""
from typing import Dict, List, Tuple

EDITIONS: List[Tuple[str, str, str, str, str]] = [
    # Caucasus and Central Asia - the hard-to-track set
    ("Armenia", "hy", "AM", "AM:hy", "hy"),
    ("Armenia (ru)", "ru", "AM", "AM:ru", "ru"),
    ("Georgia", "ka", "GE", "GE:ka", "ka"),
    ("Azerbaijan", "az", "AZ", "AZ:az", "az"),
    ("Kazakhstan", "ru", "KZ", "KZ:ru", "ru"),
    ("Uzbekistan", "ru", "UZ", "UZ:ru", "ru"),
    ("Uzbekistan (uz)", "uz", "UZ", "UZ:uz", "uz"),
    ("Ukraine", "uk", "UA", "UA:uk", "uk"),
    ("Russia", "ru", "RU", "RU:ru", "ru"),
    ("Turkey", "tr", "TR", "TR:tr", "tr"),
    # Latin America - the largest ISDS docket by respondent
    ("Mexico", "es-419", "MX", "MX:es-419", "es"),
    ("Argentina", "es-419", "AR", "AR:es-419", "es"),
    ("Colombia", "es-419", "CO", "CO:es-419", "es"),
    ("Peru", "es-419", "PE", "PE:es-419", "es"),
    ("Chile", "es-419", "CL", "CL:es-419", "es"),
    ("Spain", "es", "ES", "ES:es", "es"),
    ("Brazil", "pt-BR", "BR", "BR:pt-419", "pt"),
    ("Portugal", "pt-PT", "PT", "PT:pt-150", "pt"),
    # Francophone Africa and the Maghreb
    ("France", "fr", "FR", "FR:fr", "fr"),
    ("Senegal", "fr", "SN", "SN:fr", "fr"),
    ("Morocco", "fr", "MA", "MA:fr", "fr"),
    # Arabic
    ("Egypt", "ar", "EG", "EG:ar", "ar"),
    ("Saudi Arabia", "ar", "SA", "SA:ar", "ar"),
    ("UAE", "ar", "AE", "AE:ar", "ar"),
    # South-East Asia
    ("Indonesia", "id", "ID", "ID:id", "id"),
    ("Vietnam", "vi", "VN", "VN:vi", "vi"),
    # English editions scoped to a country - local press the global edition buries
    ("Nigeria", "en-NG", "NG", "NG:en", "en"),
    ("Kenya", "en", "KE", "KE:en", "en"),
    ("South Africa", "en-ZA", "ZA", "ZA:en", "en"),
    ("India", "en-IN", "IN", "IN:en", "en"),
    ("Pakistan", "en", "PK", "PK:en", "en"),
    ("Australia", "en-AU", "AU", "AU:en", "en"),
    ("Canada", "en-CA", "CA", "CA:en", "en"),
    ("Singapore", "en-SG", "SG", "SG:en", "en"),
    ("United Kingdom", "en-GB", "GB", "GB:en", "en"),
    ("United States", "en-US", "US", "US:en", "en"),
    ("Ireland", "en-IE", "IE", "IE:en", "en"), ("New Zealand", "en-NZ", "NZ", "NZ:en", "en"),
    ("Hong Kong", "en-HK", "HK", "HK:en", "en"), ("UAE (en)", "en-AE", "AE", "AE:en", "en"),
    ("Israel (en)", "en-IL", "IL", "IL:en", "en"), ("Philippines", "en", "PH", "PH:en", "en"),
    ("Malaysia", "en", "MY", "MY:en", "en"), ("Bangladesh", "en", "BD", "BD:en", "en"),
    ("Sri Lanka", "en", "LK", "LK:en", "en"), ("Ghana", "en", "GH", "GH:en", "en"),
    ("Tanzania", "en", "TZ", "TZ:en", "en"), ("Uganda", "en", "UG", "UG:en", "en"),
    ("Zambia", "en", "ZM", "ZM:en", "en"), ("Zimbabwe", "en", "ZW", "ZW:en", "en"),
    ("Ethiopia", "en", "ET", "ET:en", "en"), ("Botswana", "en", "BW", "BW:en", "en"), ("Namibia", "en", "NA", "NA:en", "en"),
    # more of the Spanish-, Portuguese-, French-, Arabic- and Russian-language world
    ("Ecuador", "es-419", "EC", "EC:es-419", "es"), ("Venezuela", "es-419", "VE", "VE:es-419", "es"),
    ("Bolivia", "es-419", "BO", "BO:es-419", "es"), ("Paraguay", "es-419", "PY", "PY:es-419", "es"),
    ("Uruguay", "es-419", "UY", "UY:es-419", "es"), ("Guatemala", "es-419", "GT", "GT:es-419", "es"),
    ("Dominican Republic", "es-419", "DO", "DO:es-419", "es"), ("Panama", "es-419", "PA", "PA:es-419", "es"),
    ("Costa Rica", "es-419", "CR", "CR:es-419", "es"), ("Honduras", "es-419", "HN", "HN:es-419", "es"),
    ("Mozambique", "pt-PT", "MZ", "MZ:pt-150", "pt"), ("Angola", "pt-PT", "AO", "AO:pt-150", "pt"),
    ("Belgium (fr)", "fr", "BE", "BE:fr", "fr"), ("Switzerland (fr)", "fr", "CH", "CH:fr", "fr"),
    ("Canada (fr)", "fr", "CA", "CA:fr", "fr"), ("Cote d'Ivoire", "fr", "CI", "CI:fr", "fr"),
    ("Cameroon", "fr", "CM", "CM:fr", "fr"), ("Algeria (fr)", "fr", "DZ", "DZ:fr", "fr"),
    ("Tunisia (fr)", "fr", "TN", "TN:fr", "fr"), ("DRC", "fr", "CD", "CD:fr", "fr"),
    ("Mali", "fr", "ML", "ML:fr", "fr"), ("Guinea", "fr", "GN", "GN:fr", "fr"), ("Madagascar", "fr", "MG", "MG:fr", "fr"),
    ("Iraq", "ar", "IQ", "IQ:ar", "ar"), ("Lebanon", "ar", "LB", "LB:ar", "ar"), ("Jordan", "ar", "JO", "JO:ar", "ar"),
    ("Kuwait", "ar", "KW", "KW:ar", "ar"), ("Qatar", "ar", "QA", "QA:ar", "ar"), ("Oman", "ar", "OM", "OM:ar", "ar"),
    ("Libya", "ar", "LY", "LY:ar", "ar"), ("Algeria (ar)", "ar", "DZ", "DZ:ar", "ar"),
    ("Morocco (ar)", "ar", "MA", "MA:ar", "ar"), ("Sudan", "ar", "SD", "SD:ar", "ar"),
    ("Kyrgyzstan", "ru", "KG", "KG:ru", "ru"), ("Tajikistan", "ru", "TJ", "TJ:ru", "ru"),
    ("Belarus", "ru", "BY", "BY:ru", "ru"), ("Moldova (ru)", "ru", "MD", "MD:ru", "ru"),
    ("Ukraine (ru)", "ru", "UA", "UA:ru", "ru"), ("Turkmenistan", "ru", "TM", "TM:ru", "ru"),
    # the rest of Europe, the Middle East and Asia in their own languages
    ("Germany", "de", "DE", "DE:de", "de"), ("Austria", "de", "AT", "AT:de", "de"), ("Switzerland", "de", "CH", "CH:de", "de"),
    ("Italy", "it", "IT", "IT:it", "it"), ("Poland", "pl", "PL", "PL:pl", "pl"),
    ("Netherlands", "nl", "NL", "NL:nl", "nl"), ("Belgium (nl)", "nl", "BE", "BE:nl", "nl"),
    ("Sweden", "sv", "SE", "SE:sv", "sv"), ("Norway", "no", "NO", "NO:no", "no"), ("Denmark", "da", "DK", "DK:da", "da"),
    ("Finland", "fi", "FI", "FI:fi", "fi"), ("Czechia", "cs", "CZ", "CZ:cs", "cs"), ("Slovakia", "sk", "SK", "SK:sk", "sk"),
    ("Romania", "ro", "RO", "RO:ro", "ro"), ("Hungary", "hu", "HU", "HU:hu", "hu"), ("Greece", "el", "GR", "GR:el", "el"),
    ("Bulgaria", "bg", "BG", "BG:bg", "bg"), ("Serbia", "sr", "RS", "RS:sr", "sr"), ("Croatia", "hr", "HR", "HR:hr", "hr"),
    ("Slovenia", "sl", "SI", "SI:sl", "sl"), ("Lithuania", "lt", "LT", "LT:lt", "lt"), ("Latvia", "lv", "LV", "LV:lv", "lv"),
    ("Estonia", "et", "EE", "EE:et", "et"), ("Israel", "he", "IL", "IL:he", "he"), ("India (hi)", "hi", "IN", "IN:hi", "hi"),
    ("Bangladesh (bn)", "bn", "BD", "BD:bn", "bn"), ("Japan", "ja", "JP", "JP:ja", "ja"), ("Korea", "ko", "KR", "KR:ko", "ko"),
    ("China", "zh-CN", "CN", "CN:zh-Hans", "zh"), ("Taiwan", "zh-TW", "TW", "TW:zh-Hant", "zh"),
    ("Hong Kong (zh)", "zh-HK", "HK", "HK:zh-Hant", "zh"), ("Thailand", "th", "TH", "TH:th", "th"),
    ("Malaysia (ms)", "ms", "MY", "MY:ms", "ms"),
]

TERMS: Dict[str, List[str]] = {
    "en": ['arbitration (ICSID OR "investment treaty" OR "international arbitration") government -referee -football',
           '(expropriation OR nationalisation OR nationalization OR "licence revoked" OR "license revoked") investor',
           '("notice of dispute" OR "notice of intent" OR "notice of arbitration") (treaty OR government)'],
    "hy": ['(արբիտրաժ OR ICSID) (ներդրող OR միջազգային OR պետություն)',
           'ազգայնացում OR բռնագրավում OR "օտարերկրյա ներդրող"',
           '"ներդրումային վեճ" OR "ներդրումային համաձայնագիր"'],
    "ka": ['(არბიტრაჟი OR ICSID) (ინვესტორი OR საერთაშორისო OR სახელმწიფო) -ფეხბურთი',
           'ექსპროპრიაცია OR ნაციონალიზაცია OR "უცხოელი ინვესტორი"',
           '"საინვესტიციო დავა" OR "საინვესტიციო ხელშეკრულება"'],
    "az": ['(arbitraj OR ICSID) (investor OR beynəlxalq OR dövlət) -futbol',
           'ekspropriasiya OR milliləşdirmə OR "xarici investor"',
           '"investisiya mübahisəsi" OR "investisiya sazişi"'],
    "ru": ['(арбитраж OR ICSID OR МЦУИС) (инвестор OR международный OR государство OR иск) -футбол -судья',
           '(экспроприация OR национализация OR "отзыв лицензии") (инвестор OR компания OR иностранн)',
           '"инвестиционный спор" OR "инвестиционное соглашение" OR "уведомление о споре"'],
    "uk": ['(арбітраж OR ICSID) (інвестор OR міжнародний OR держава OR позов) -футбол',
           '(експропріація OR націоналізація) (інвестор OR компанія)',
           '"інвестиційний спір" OR "інвестиційна угода"'],
    "uz": ['(arbitraj OR ICSID) (investor OR xalqaro OR davlat) -futbol',
           'ekspropriatsiya OR milliylashtirish OR "xorijiy investor"',
           '"investitsiya nizosi"'],
    "tr": ['(tahkim OR ICSID) (yatırımcı OR uluslararası OR devlet OR dava) -maç -hakem',
           '(kamulaştırma OR millileştirme OR "lisans iptali") (yabancı OR yatırımcı OR şirket) -"acele kamulaştırma"',
           '"yatırım anlaşmazlığı" OR "yatırım uyuşmazlığı" OR "ikili yatırım anlaşması"'],
    "es": ['(arbitraje OR CIADI) (inversión OR inversionista OR inversor OR internacional OR Estado) -fútbol -árbitro -liga',
           '(expropiación OR nacionalización OR "revocación de licencia") (inversionista OR inversor OR empresa OR extranjer)',
           '"tratado bilateral de inversión" OR "controversia de inversión" OR "notificación de controversia"'],
    "pt": ['(arbitragem OR CIRDI OR ICSID) (investimento OR investidor OR internacional OR Estado) -futebol -árbitro',
           '(expropriação OR desapropriação OR nacionalização) (investidor OR empresa OR estrangeir)',
           '"tratado de investimento" OR "disputa de investimento"'],
    "fr": ['(arbitrage OR CIRDI) (investissement OR investisseur OR international OR État) -football -match -arbitre',
           '(expropriation OR nationalisation OR "retrait de licence") (investisseur OR entreprise OR étranger)',
           '"traité bilatéral d\'investissement" OR "différend relatif aux investissements"'],
    "ar": ['("التحكيم الدولي" OR "المركز الدولي لتسوية منازعات الاستثمار") -مباراة -كرة',
           '(مصادرة OR تأميم) (مستثمر OR شركة OR أجنبي)',
           '"نزاع استثماري" OR "اتفاقية استثمار"'],
    "id": ['(arbitrase OR ICSID) (investor OR internasional OR pemerintah) -sepak',
           '(nasionalisasi OR pengambilalihan OR "pencabutan izin") (investor OR asing OR perusahaan)',
           '"sengketa investasi" OR "perjanjian investasi"'],
    "vi": ['"trọng tài quốc tế" OR ICSID -bóng',
           '("quốc hữu hóa" OR "thu hồi giấy phép") ("nhà đầu tư" OR "doanh nghiệp")',
           '"tranh chấp đầu tư"'],
    "de": ['(Schiedsverfahren OR Schiedsgericht OR Schiedsspruch OR ICSID) (Investor OR international OR Staat OR Klage) -Schiedsrichter -Fußball',
           '(Enteignung OR Verstaatlichung OR "Lizenz entzogen" OR "Konzession entzogen") (Investor OR Unternehmen OR ausländisch)',
           '"Investitionsschutz" OR "Investitionsstreit" OR "Investitionsschutzabkommen"'],
    "it": ['(arbitrato OR ICSID OR "tribunale arbitrale") (investitore OR internazionale OR Stato OR causa) -arbitro -calcio',
           '(esproprio OR espropriazione OR nazionalizzazione OR "revoca della licenza") (investitore OR società OR straniero)',
           '"trattato bilaterale di investimento" OR "controversia di investimento"'],
    "pl": ['(arbitraż OR ICSID OR "trybunał arbitrażowy") (inwestor OR międzynarodowy OR państwo OR pozew) -sędzia -piłka',
           '(wywłaszczenie OR nacjonalizacja OR "cofnięcie koncesji") (inwestor OR spółka OR zagraniczny)',
           '"umowa o ochronie inwestycji" OR "spór inwestycyjny"'],
    "nl": ['(arbitrage OR ICSID OR scheidsgerecht) (investeerder OR internationaal OR staat OR claim) -scheidsrechter -voetbal',
           '(onteigening OR nationalisatie OR "vergunning ingetrokken") (investeerder OR bedrijf OR buitenlands)',
           '"investeringsverdrag" OR "investeringsgeschil"'],
    "sv": ['(skiljeförfarande OR skiljedom OR ICSID) (investerare OR internationell OR staten) -fotboll -domare',
           '(expropriation OR förstatligande) (investerare OR bolag OR utländsk)',
           '"investeringsskyddsavtal" OR "investeringstvist"'],
    "no": ['(voldgift OR ICSID) (investor OR internasjonal OR staten) -fotball',
           '(ekspropriasjon OR nasjonalisering) (investor OR selskap OR utenlandsk)',
           '"investeringsavtale" OR "investeringstvist"'],
    "da": ['(voldgift OR ICSID) (investor OR international OR staten) -fodbold',
           '(ekspropriation OR nationalisering) (investor OR selskab OR udenlandsk)',
           '"investeringsaftale" OR "investeringstvist"'],
    "fi": ['(välimiesmenettely OR välitystuomio OR ICSID) (sijoittaja OR kansainvälinen OR valtio) -jalkapallo',
           '(pakkolunastus OR kansallistaminen) (sijoittaja OR yhtiö OR ulkomainen)',
           '"investointisuojasopimus" OR "investointiriita"'],
    "cs": ['(arbitráž OR "rozhodčí řízení" OR ICSID) (investor OR mezinárodní OR stát OR žaloba) -fotbal -rozhodčí',
           '(vyvlastnění OR znárodnění OR "odebrání licence") (investor OR firma OR zahraniční)',
           '"dohoda o ochraně investic" OR "investiční spor"'],
    "sk": ['(arbitráž OR "rozhodcovské konanie" OR ICSID) (investor OR medzinárodný OR štát) -futbal',
           '(vyvlastnenie OR znárodnenie) (investor OR firma OR zahraničný)',
           '"dohoda o ochrane investícií" OR "investičný spor"'],
    "ro": ['(arbitraj OR ICSID OR "tribunal arbitral") (investitor OR internațional OR stat OR proces) -fotbal -arbitru',
           '(expropriere OR naționalizare OR "retragerea licenței") (investitor OR companie OR străin)',
           '"tratat de investiții" OR "litigiu de investiții"'],
    "hu": ['(választottbíróság OR választottbírósági OR ICSID) (befektető OR nemzetközi OR állam OR per) -foci -játékvezető',
           '(kisajátítás OR államosítás OR "engedély visszavonása") (befektető OR cég OR külföldi)',
           '"beruházásvédelmi megállapodás" OR "beruházási vita"'],
    "el": ['(διαιτησία OR ICSID OR "διαιτητικό δικαστήριο") (επενδυτής OR διεθνής OR κράτος OR αγωγή) -ποδόσφαιρο -διαιτητής',
           '(απαλλοτρίωση OR εθνικοποίηση OR "ανάκληση άδειας") (επενδυτής OR εταιρεία OR ξένος)',
           '"επενδυτική διαφορά" OR "διμερής επενδυτική συμφωνία"'],
    "bg": ['(арбитраж OR ICSID OR "арбитражен съд") (инвеститор OR международен OR държава OR иск) -футбол -съдия',
           '(отчуждаване OR национализация OR "отнемане на лиценз") (инвеститор OR компания OR чуждестранен)',
           '"инвестиционен спор" OR "договор за защита на инвестициите"'],
    "sr": ['(arbitraža OR арбитража OR ICSID) (investitor OR инвеститор OR međunarodni OR država) -fudbal -sudija',
           '(eksproprijacija OR nacionalizacija OR "oduzimanje licence") (investitor OR kompanija OR strani)',
           '"investicioni spor" OR "sporazum o zaštiti investicija"'],
    "hr": ['(arbitraža OR ICSID) (investitor OR ulagač OR međunarodni OR država) -nogomet -sudac',
           '(izvlaštenje OR nacionalizacija OR "oduzimanje koncesije") (ulagač OR tvrtka OR strani)',
           '"investicijski spor" OR "ugovor o zaštiti ulaganja"'],
    "sl": ['(arbitraža OR ICSID) (vlagatelj OR investitor OR mednarodni OR država) -nogomet -sodnik',
           '(razlastitev OR nacionalizacija) (vlagatelj OR podjetje OR tuji)',
           '"investicijski spor" OR "sporazum o zaščiti naložb"'],
    "lt": ['(arbitražas OR ICSID) (investuotojas OR tarptautinis OR valstybė) -futbolas -teisėjas',
           '(nusavinimas OR nacionalizavimas) (investuotojas OR įmonė OR užsienio)',
           '"investicijų ginčas" OR "investicijų apsaugos sutartis"'],
    "lv": ['(arbitrāža OR šķīrējtiesa OR ICSID) (investors OR starptautisks OR valsts) -futbols -tiesnesis',
           '(ekspropriācija OR nacionalizācija) (investors OR uzņēmums OR ārvalstu)',
           '"investīciju strīds" OR "investīciju aizsardzības līgums"'],
    "et": ['(vahekohus OR arbitraaž OR ICSID) (investor OR rahvusvaheline OR riik) -jalgpall -kohtunik',
           '(sundvõõrandamine OR natsionaliseerimine) (investor OR ettevõte OR välismaine)',
           '"investeeringute kaitse leping" OR "investeeringuvaidlus"'],
    "he": ['(בוררות OR ICSID) (משקיע OR בינלאומי OR מדינה OR תביעה) -כדורגל -שופט',
           '(הפקעה OR הלאמה OR "ביטול רישיון") (משקיע OR חברה OR זר)',
           '"סכסוך השקעות" OR "הסכם להגנת השקעות"'],
    "hi": ['(मध्यस्थता OR ICSID) (निवेशक OR अंतरराष्ट्रीय OR सरकार OR दावा) -क्रिकेट -फुटबॉल',
           '(अधिग्रहण OR राष्ट्रीयकरण OR "लाइसेंस रद्द") (निवेशक OR कंपनी OR विदेशी)',
           '"निवेश विवाद" OR "द्विपक्षीय निवेश संधि"'],
    "bn": ['(সালিশ OR সালিশি OR ICSID) (বিনিয়োগকারী OR আন্তর্জাতিক OR সরকার) -ক্রিকেট -ফুটবল',
           '(অধিগ্রহণ OR জাতীয়করণ OR "লাইসেন্স বাতিল") (বিনিয়োগকারী OR কোম্পানি OR বিদেশি)',
           '"বিনিয়োগ বিরোধ"'],
    "ja": ['(国際仲裁 OR 仲裁判断 OR ICSID OR 投資仲裁) -サッカー -審判',
           '(収用 OR 国有化 OR 免許取消) (投資家 OR 企業 OR 外国)',
           '"投資協定" OR "投資紛争"'],
    "ko": ['(국제중재 OR 중재판정 OR ICSID OR 투자중재) -축구 -심판',
           '(수용 OR 국유화 OR 면허취소) (투자자 OR 기업 OR 외국)',
           '"투자협정" OR "투자분쟁" OR ISDS'],
    "zh": ['(国际仲裁 OR 仲裁裁决 OR ICSID OR 投资仲裁 OR 國際仲裁 OR 仲裁裁決) -足球 -裁判',
           '(征收 OR 国有化 OR 吊销许可证 OR 徵收 OR 國有化) (投资者 OR 企业 OR 外国 OR 投資者 OR 外資)',
           '"投资协定" OR "投资争端" OR "投資協定" OR "投資爭端"'],
    "th": ['(อนุญาโตตุลาการ OR ICSID) (นักลงทุน OR ระหว่างประเทศ OR รัฐบาล) -ฟุตบอล',
           '(เวนคืน OR โอนเป็นของรัฐ OR "เพิกถอนใบอนุญาต") (นักลงทุน OR บริษัท OR ต่างชาติ)',
           '"ข้อพิพาทการลงทุน" OR "ความตกลงคุ้มครองการลงทุน"'],
    "ms": ['("timbang tara" OR ICSID) (pelabur OR antarabangsa OR kerajaan) -bola',
           '(pengambilan OR pemiliknegaraan OR "lesen dibatalkan") (pelabur OR syarikat OR asing)',
           '"pertikaian pelaburan" OR "perjanjian pelaburan"'],
}

LANG_NAMES = {"hy": "Armenian", "ka": "Georgian", "az": "Azerbaijani", "ru": "Russian",
              "uk": "Ukrainian", "uz": "Uzbek", "tr": "Turkish", "es": "Spanish",
              "pt": "Portuguese", "fr": "French", "ar": "Arabic", "id": "Indonesian",
              "vi": "Vietnamese", "en": "English", "de": "German", "it": "Italian", "pl": "Polish",
              "nl": "Dutch", "sv": "Swedish", "no": "Norwegian", "da": "Danish", "fi": "Finnish",
              "cs": "Czech", "sk": "Slovak", "ro": "Romanian", "hu": "Hungarian", "el": "Greek",
              "bg": "Bulgarian", "sr": "Serbian", "hr": "Croatian", "sl": "Slovenian", "lt": "Lithuanian",
              "lv": "Latvian", "et": "Estonian", "he": "Hebrew", "hi": "Hindi", "bn": "Bengali",
              "ja": "Japanese", "ko": "Korean", "zh": "Chinese", "th": "Thai", "ms": "Malay"}


# Foreign investors with the balance sheet to instruct. A State measure against one
# of these is a lead even when nobody has said the word "arbitration" yet.
MAJORS = [
    # mining and metals
    "Glencore", "Rio Tinto", "BHP", "Anglo American", "Barrick", "Newmont", "First Quantum",
    "Freeport", "Vale", "Teck", "Antofagasta", "Southern Copper", "Ivanhoe", "AngloGold",
    "Gold Fields", "Kinross", "B2Gold", "Endeavour Mining", "Centamin", "Fortescue",
    "Lundin", "Eramet", "Albemarle", "SQM", "Ganfeng", "Tianqi", "Zijin", "CMOC",
    # oil and gas
    "TotalEnergies", "Shell", "BP", "Chevron", "ExxonMobil", "Eni", "Equinor", "Repsol",
    "Galp", "OMV", "Woodside", "Santos", "Tullow", "Kosmos", "Perenco", "Vitol", "Trafigura",
    "Gunvor", "Chariot", "Genel", "Gulf Keystone", "DNO", "Maurel", "Africa Oil",
    # power and utilities
    "Enel", "Iberdrola", "EDF", "Engie", "RWE", "Vattenfall", "Ørsted", "Orsted", "Scatec",
    "Globeleq", "ACWA", "Masdar", "AES", "Veolia", "Suez", "Acciona", "Naturgy", "EDP",
    # telecoms and tech
    "Vodafone", "Telefónica", "Telefonica", "MTN", "Orange", "Airtel", "Millicom", "Veon",
    "Ooredoo", "Zain", "Etisalat", "Meta", "Google", "Amazon", "Microsoft", "Apple", "Uber",
    "Oracle", "Starlink", "SpaceX",
    # consumer, pharma, finance, infrastructure
    "Nestlé", "Nestle", "Unilever", "AB InBev", "Philip Morris", "British American Tobacco",
    "Coca-Cola", "PepsiCo", "Diageo", "Heineken", "Carlsberg", "Pfizer", "Novartis", "Roche",
    "Sanofi", "AstraZeneca", "Bayer", "Siemens", "Alstom", "Bombardier", "Airbus", "Boeing",
    "Vinci", "Bouygues", "Eiffage", "Ferrovial", "ACS", "Sacyr", "Strabag", "Salini", "Webuild",
    "DP World", "APM Terminals", "Maersk", "MSC", "CMA CGM", "Hutchison", "PSA International",
    "HSBC", "Citi", "Standard Chartered", "Société Générale", "BNP Paribas", "Santander",
    "BBVA", "Scotiabank", "Blackstone", "KKR", "Brookfield", "Macquarie", "Actis", "Carlyle",
]

# Measures a State takes that map onto treaty standards: expropriation, fair and
# equitable treatment, umbrella clause, transfers. Queried in the editions' languages.
MEASURES: Dict[str, List[str]] = {
    "en": ['(revokes OR revoked OR cancels OR cancelled OR terminates OR terminated) (licence OR license OR concession OR permit OR contract) (foreign OR international OR "-owned" OR investor OR company)',
           '("tax assessment" OR "back taxes" OR "windfall tax" OR "retroactive tax" OR "tax demand") (mining OR oil OR gas OR telecom OR "foreign company" OR multinational) (billion OR million)',
           '(nationalise OR nationalize OR nationalisation OR nationalization OR expropriate OR expropriation OR "takes control" OR seizes OR seized) (mine OR plant OR refinery OR company OR assets OR subsidiary) government',
           '(government OR ministry OR regulator OR president OR decree) (suspends OR halts OR freezes OR blocks OR bans) (exports OR operations OR project OR licence OR dividends OR transfers) (foreign OR investor OR company)',
           '("renegotiate" OR "review" OR "reopen") (contract OR concession OR "production sharing" OR "power purchase" OR PPA OR tariff) government (foreign OR investor OR company)'],
    "es": ['(revoca OR revocó OR cancela OR canceló OR rescinde OR rescindió OR caduca) (licencia OR concesión OR permiso OR contrato) (extranjera OR extranjero OR inversionista OR empresa OR minera OR petrolera)',
           '(expropia OR expropiación OR nacionaliza OR nacionalización OR "toma el control" OR incauta OR embarga) (mina OR planta OR empresa OR activos OR filial) gobierno',
           '(gobierno OR ministerio OR decreto OR regulador) (suspende OR bloquea OR prohíbe OR congela) (exportaciones OR operaciones OR proyecto OR tarifa OR dividendos) (extranjera OR inversionista OR empresa)',
           '("renegociar" OR "revisar" OR "reabrir") (contrato OR concesión OR tarifa OR "contrato de exploración") gobierno (extranjera OR inversionista OR empresa)'],
    "fr": ['(retire OR retrait OR annule OR annulation OR résilie OR résiliation) (licence OR permis OR concession OR contrat) (étrangère OR étranger OR investisseur OR société OR minière OR pétrolière)',
           '(nationalise OR nationalisation OR exproprie OR expropriation OR saisit OR saisie OR "prend le contrôle") (mine OR usine OR société OR actifs OR filiale) gouvernement',
           '(gouvernement OR ministère OR décret OR régulateur) (suspend OR bloque OR interdit OR gèle) (exportations OR activités OR projet OR tarif OR dividendes) (étrangère OR investisseur OR société)'],
    "ru": ['(отзыв OR отозвал OR аннулировал OR расторг OR лишил) (лицензии OR лицензию OR концессии OR контракта OR разрешения) (иностранн OR инвестор OR компани)',
           '(национализац OR экспроприац OR изъятие OR арест OR "передан в собственность государства") (завод OR рудник OR месторождение OR компани OR активы OR доля) (иностранн OR инвестор)',
           '(правительство OR министерство OR указ OR суд) (приостановил OR запретил OR заморозил OR заблокировал) (экспорт OR деятельность OR проект OR дивиденды OR вывод) (иностранн OR инвестор OR компани)',
           '(доначислил OR доначисление OR "налоговые претензии" OR "налоговая проверка") (иностранн OR компани) (млрд OR миллиард OR млн)'],
    "tr": ['(iptal OR iptal etti OR feshetti OR askıya aldı) (lisans OR ruhsat OR imtiyaz OR sözleşme) (yabancı OR yatırımcı OR şirket)',
           '(kamulaştırma OR millileştirme OR "el koydu" OR "el konuldu" OR TMSF) (şirket OR maden OR santral OR varlık) (yabancı OR yatırımcı)'],
    "pt": ['(revoga OR revogou OR cancela OR cancelou OR rescinde OR rescindiu) (licença OR concessão OR contrato OR alvará) (estrangeira OR estrangeiro OR investidor OR empresa OR mineradora OR petrolífera)',
           '(nacionaliza OR nacionalização OR expropria OR expropriação OR "assume o controle") (mina OR fábrica OR empresa OR ativos OR subsidiária) governo'],
    "ar": ['(إلغاء OR سحب OR فسخ OR تعليق) (رخصة OR ترخيص OR امتياز OR عقد) (أجنبية OR أجنبي OR مستثمر OR شركة)',
           '(تأميم OR مصادرة OR "الاستيلاء على") (شركة OR منجم OR مصنع OR أصول) (أجنبية OR مستثمر)'],
    "id": ['(mencabut OR pencabutan OR membatalkan OR menghentikan) (izin OR IUP OR konsesi OR kontrak) (asing OR investor OR perusahaan)',
           '(nasionalisasi OR pengambilalihan OR menyita OR "mengambil alih") (tambang OR pabrik OR perusahaan OR aset OR saham) pemerintah (asing OR investor)'],
    "uk": ['(анулював OR анулювання OR скасував OR розірвав OR позбавив) (ліцензії OR ліцензію OR концесії OR контракту OR дозволу) (іноземн OR інвестор OR компані)',
           '(націоналізац OR експропріац OR арешт OR вилучення OR "передано державі") (завод OR родовище OR компані OR активи OR частка) (іноземн OR інвестор)'],
    "hy": ['(լիցենզիա OR թույլտվություն OR պայմանագիր) (զրկել OR դադարեցնել OR չեղարկել) (օտարերկրյա OR ներդրող OR ընկերություն)',
           '(ազգայնացում OR բռնագրավում OR արգելանք) (ընկերություն OR հանք OR գործարան OR ակտիվներ) (օտարերկրյա OR ներդրող)'],
    "ka": ['(გაუქმება OR შეჩერება OR ჩამორთმევა) (ლიცენზია OR ნებართვა OR კონცესია OR კონტრაქტი) (უცხოური OR ინვესტორი OR კომპანია)',
           '(ნაციონალიზაცია OR ექსპროპრიაცია OR დაყადაღება OR "ჩამორთმევა") (კომპანია OR საწარმო OR აქტივები) (უცხოური OR ინვესტორი)'],
    "az": ['(ləğv OR dayandırıl OR geri alın) (lisenziya OR icazə OR konsessiya OR müqavilə) (xarici OR investor OR şirkət)',
           '(milliləşdirmə OR müsadirə OR "həbs qoyul") (şirkət OR mədən OR zavod OR aktiv) (xarici OR investor)'],
    "vi": ['("thu hồi" OR "hủy bỏ" OR "đình chỉ" OR "chấm dứt") ("giấy phép" OR "hợp đồng" OR "dự án") ("nhà đầu tư nước ngoài" OR "doanh nghiệp FDI" OR "công ty nước ngoài")'],
    "uz": ['(bekor OR toʻxtatildi OR "qaytarib olindi") (litsenziya OR ruxsatnoma OR shartnoma OR kontsessiya) (xorijiy OR investor OR kompaniya)'],
}


# State names and demonyms -> canonical State. Used to answer "who" for a press
# item that no model has read yet.
COUNTRIES = {}
for _canon, _forms in {
    "Argentina": ["Argentina", "Argentine", "Argentinian"], "Armenia": ["Armenia", "Armenian"],
    "Australia": ["Australia", "Australian"], "Azerbaijan": ["Azerbaijan", "Azerbaijani", "Azeri"],
    "Belgium": ["Belgium", "Belgian"], "Bolivia": ["Bolivia", "Bolivian"], "Brazil": ["Brazil", "Brazilian"],
    "Bulgaria": ["Bulgaria", "Bulgarian"], "Burkina Faso": ["Burkina Faso", "Burkinabe"],
    "Cameroon": ["Cameroon", "Cameroonian"], "Canada": ["Canada", "Canadian"], "Chile": ["Chile", "Chilean"],
    "China": ["China", "Chinese"], "Colombia": ["Colombia", "Colombian"], "Congo (DRC)": ["DRC", "Congo", "Congolese"],
    "Croatia": ["Croatia", "Croatian"], "Cyprus": ["Cyprus", "Cypriot"], "Czechia": ["Czech Republic", "Czechia", "Czech"],
    "Ecuador": ["Ecuador", "Ecuadorian", "Ecuadorean"], "Egypt": ["Egypt", "Egyptian"],
    "Georgia": ["Georgia", "Georgian"], "Germany": ["Germany", "German"], "Ghana": ["Ghana", "Ghanaian"],
    "Greece": ["Greece", "Greek"], "Guatemala": ["Guatemala", "Guatemalan"], "Guinea": ["Guinea", "Guinean"],
    "Honduras": ["Honduras", "Honduran"], "Hungary": ["Hungary", "Hungarian"], "India": ["India", "Indian"],
    "Indonesia": ["Indonesia", "Indonesian"], "Iraq": ["Iraq", "Iraqi"], "Ireland": ["Ireland", "Irish"],
    "Italy": ["Italy", "Italian"], "Kazakhstan": ["Kazakhstan", "Kazakh"], "Kenya": ["Kenya", "Kenyan"],
    "Korea": ["South Korea", "Korea", "Korean"], "Kyrgyzstan": ["Kyrgyzstan", "Kyrgyz"], "Lebanon": ["Lebanon", "Lebanese"],
    "Libya": ["Libya", "Libyan"], "Malaysia": ["Malaysia", "Malaysian"], "Mali": ["Mali", "Malian"],
    "Malta": ["Malta", "Maltese"], "Mexico": ["Mexico", "Mexican"], "Moldova": ["Moldova", "Moldovan"],
    "Mongolia": ["Mongolia", "Mongolian"], "Montenegro": ["Montenegro", "Montenegrin"], "Morocco": ["Morocco", "Moroccan"],
    "Mozambique": ["Mozambique", "Mozambican"], "Netherlands": ["Netherlands", "Dutch"], "Niger": ["Niger", "Nigerien"],
    "Nigeria": ["Nigeria", "Nigerian"], "Norway": ["Norway", "Norwegian"], "Pakistan": ["Pakistan", "Pakistani"],
    "Panama": ["Panama", "Panamanian"], "Paraguay": ["Paraguay", "Paraguayan"], "Peru": ["Peru", "Peruvian"],
    "Philippines": ["Philippines", "Philippine", "Filipino"], "Poland": ["Poland", "Polish"], "Portugal": ["Portugal", "Portuguese"],
    "Qatar": ["Qatar", "Qatari"], "Romania": ["Romania", "Romanian"], "Russia": ["Russia", "Russian", "Kremlin", "Putin"],
    "Saudi Arabia": ["Saudi Arabia", "Saudi"], "Senegal": ["Senegal", "Senegalese"], "Serbia": ["Serbia", "Serbian"],
    "Slovakia": ["Slovakia", "Slovak"], "Slovenia": ["Slovenia", "Slovenian"], "South Africa": ["South Africa", "South African"],
    "Spain": ["Spain", "Spanish"], "Sri Lanka": ["Sri Lanka", "Sri Lankan"], "Tanzania": ["Tanzania", "Tanzanian"],
    "Tajikistan": ["Tajikistan", "Tajik"], "Turkey": ["Turkey", "Türkiye", "Turkish"], "Turkmenistan": ["Turkmenistan", "Turkmen"],
    "Uganda": ["Uganda", "Ugandan"], "Ukraine": ["Ukraine", "Ukrainian"], "United Arab Emirates": ["UAE", "United Arab Emirates", "Emirati"],
    "United Kingdom": ["United Kingdom", "Britain", "British", "UK"], "United States": ["United States", "U.S.", "US government"],
    "Uruguay": ["Uruguay", "Uruguayan"], "Uzbekistan": ["Uzbekistan", "Uzbek"], "Venezuela": ["Venezuela", "Venezuelan"],
    "Vietnam": ["Vietnam", "Vietnamese"], "Zambia": ["Zambia", "Zambian"], "Zimbabwe": ["Zimbabwe", "Zimbabwean"],
    "Algeria": ["Algeria", "Algerian"], "Angola": ["Angola", "Angolan"], "Bangladesh": ["Bangladesh", "Bangladeshi"],
    "Bosnia and Herzegovina": ["Bosnia", "Bosnian"], "Costa Rica": ["Costa Rica", "Costa Rican"], "Dominican Republic": ["Dominican Republic", "Dominican"],
    "El Salvador": ["El Salvador", "Salvadoran"], "Ethiopia": ["Ethiopia", "Ethiopian"], "Jordan": ["Jordan", "Jordanian"],
    "Kuwait": ["Kuwait", "Kuwaiti"], "Laos": ["Laos", "Lao"], "Latvia": ["Latvia", "Latvian"], "Lithuania": ["Lithuania", "Lithuanian"],
    "Madagascar": ["Madagascar", "Malagasy"], "Myanmar": ["Myanmar", "Burmese"], "Nicaragua": ["Nicaragua", "Nicaraguan"],
    "Oman": ["Oman", "Omani"], "Papua New Guinea": ["Papua New Guinea", "PNG"], "Sierra Leone": ["Sierra Leone"],
    "Sudan": ["Sudan", "Sudanese"], "Tunisia": ["Tunisia", "Tunisian"], "Yemen": ["Yemen", "Yemeni"],
}.items():
    for _f in _forms:
        COUNTRIES[_f] = _canon

_COUNTRY_RE = None


def states_in(text: str):
    """Canonical States named in a text, longest form first, whole words only."""
    global _COUNTRY_RE
    if _COUNTRY_RE is None:
        forms = sorted(COUNTRIES, key=len, reverse=True)
        _COUNTRY_RE = __import__("re").compile(r"(?<![\w-])(" + "|".join(__import__("re").escape(f) for f in forms) + r")(?![\w-])")
    out = []
    for m in _COUNTRY_RE.finditer(text or ""):
        c = COUNTRIES[m.group(1)]
        if c not in out:
            out.append(c)
    return out
